spring:
  config:
    import: file:.env
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${HOST}:3306/empresa_x?useTimezone-true&serverTimezone=UTC
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
